// Java generated by Techne

package com.kraz.minehr.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelCrab extends ModelBase
{
    //fields
    ModelRenderer Body;
    ModelRenderer Leg;
    ModelRenderer Leg2;
    ModelRenderer Leg3;
    ModelRenderer Leg4;
    ModelRenderer Leg5;
    ModelRenderer Leg6;
    ModelRenderer arm1;
    ModelRenderer arm2;
    ModelRenderer Claw1;
    ModelRenderer Claw2;

    public ModelCrab()
    {
        textureWidth = 32;
        textureHeight = 32;

        Body = new ModelRenderer(this, 0, 0);
        Body.addBox(0F, 0F, 0F, 6, 3, 5);
        Body.setRotationPoint(-3F, 21F, -2F);
        Body.setTextureSize(32, 32);
        Body.mirror = true;
        setRotation(Body, 0F, 0F, 0F);
        Leg = new ModelRenderer(this, 17, 0);
        Leg.addBox(0F, 0F, 0F, 4, 1, 1);
        Leg.setRotationPoint(3F, 22F, 0F);
        Leg.setTextureSize(32, 32);
        Leg.mirror = true;
        setRotation(Leg, 0F, 0F, 0.3490659F);
        Leg2 = new ModelRenderer(this, 17, 2);
        Leg2.addBox(-4F, 0F, 0F, 4, 1, 1);
        Leg2.setRotationPoint(-3F, 22F, 0F);
        Leg2.setTextureSize(32, 32);
        Leg2.mirror = true;
        setRotation(Leg2, 0F, 0F, -0.3490659F);
        Leg3 = new ModelRenderer(this, 0, 8);
        Leg3.addBox(0F, 0F, 0F, 4, 1, 1);
        Leg3.setRotationPoint(3F, 22F, 2F);
        Leg3.setTextureSize(32, 32);
        Leg3.mirror = true;
        setRotation(Leg3, 0F, -0.7853982F, 0.3490659F);
        Leg4 = new ModelRenderer(this, 10, 8);
        Leg4.addBox(-4F, 0F, 0F, 4, 1, 1);
        Leg4.setRotationPoint(-3F, 22F, 2F);
        Leg4.setTextureSize(32, 32);
        Leg4.mirror = true;
        setRotation(Leg4, 0F, 0.7853982F, -0.3490659F);
        Leg5 = new ModelRenderer(this, 0, 10);
        Leg5.addBox(0F, 0F, 0F, 4, 1, 1);
        Leg5.setRotationPoint(2F, 22F, -2F);
        Leg5.setTextureSize(32, 32);
        Leg5.mirror = true;
        setRotation(Leg5, 0F, 0.2617994F, 0.3490659F);
        Leg6 = new ModelRenderer(this, 10, 10);
        Leg6.addBox(-4F, 0F, 0F, 4, 1, 1);
        Leg6.setRotationPoint(-2F, 22F, -2F);
        Leg6.setTextureSize(32, 32);
        Leg6.mirror = true;
        setRotation(Leg6, 0F, -0.2617994F, -0.3490659F);
        arm1 = new ModelRenderer(this, 20, 8);
        arm1.addBox(0F, 0F, 0F, 2, 1, 1);
        arm1.setRotationPoint(0F, 22F, -2F);
        arm1.setTextureSize(32, 32);
        arm1.mirror = true;
        setRotation(arm1, 0F, 1.308997F, 0F);
        arm2 = new ModelRenderer(this, 20, 10);
        arm2.addBox(0F, 0F, 0F, 2, 1, 1);
        arm2.setRotationPoint(-1F, 22F, -1.7F);
        arm2.setTextureSize(32, 32);
        arm2.mirror = true;
        setRotation(arm2, 0F, 1.832596F, 0F);
        Claw1 = new ModelRenderer(this, 0, 12);
        Claw1.addBox(0F, 0F, 0F, 2, 1, 2);
        Claw1.setRotationPoint(0.5F, 22F, -5.5F);
        Claw1.setTextureSize(32, 32);
        Claw1.mirror = true;
        setRotation(Claw1, 0F, 0F, 0F);
        Claw2 = new ModelRenderer(this, 8, 12);
        Claw2.addBox(0F, 0F, 0F, 2, 1, 2);
        Claw2.setRotationPoint(-2.5F, 22F, -5.5F);
        Claw2.setTextureSize(32, 32);
        Claw2.mirror = true;
        setRotation(Claw2, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Body.render(f5);
        Leg.render(f5);
        Leg2.render(f5);
        Leg3.render(f5);
        Leg4.render(f5);
        Leg5.render(f5);
        Leg6.render(f5);
        arm1.render(f5);
        arm2.render(f5);
        Claw1.render(f5);
        Claw2.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
    {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}
