// Date: 10/14/2014 8:43:53 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.kraz.minehr.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelLobsterTrap extends ModelBase
{
  //fields
    ModelRenderer Top;
    ModelRenderer Bottom;
    ModelRenderer Post1;
    ModelRenderer Post2;
    ModelRenderer Post3;
    ModelRenderer Post4;
    ModelRenderer Net;
  
  public ModelLobsterTrap()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      Top = new ModelRenderer(this, 0, 0);
      Top.addBox(-8F, 0F, -8F, 16, 1, 16);
      Top.setRotationPoint(0F, 14F, 0F);
      Top.setTextureSize(64, 64);
      Top.mirror = true;
      setRotation(Top, 0F, 0F, 0F);
      Bottom = new ModelRenderer(this, 0, 0);
      Bottom.addBox(-8F, 0F, -8F, 16, 1, 16);
      Bottom.setRotationPoint(0F, 23F, 0F);
      Bottom.setTextureSize(64, 64);
      Bottom.mirror = true;
      setRotation(Bottom, 0F, 0F, 0F);
      Post1 = new ModelRenderer(this, 0, 0);
      Post1.addBox(0F, -4F, 0F, 1, 8, 1);
      Post1.setRotationPoint(6F, 19F, -7F);
      Post1.setTextureSize(64, 64);
      Post1.mirror = true;
      setRotation(Post1, 0F, 0F, 0F);
      Post2 = new ModelRenderer(this, 0, 0);
      Post2.addBox(0F, 0F, 0F, 1, 8, 1);
      Post2.setRotationPoint(6F, 15F, 6F);
      Post2.setTextureSize(64, 64);
      Post2.mirror = true;
      setRotation(Post2, 0F, 0F, 0F);
      Post3 = new ModelRenderer(this, 0, 0);
      Post3.addBox(0F, 0F, 0F, 1, 8, 1);
      Post3.setRotationPoint(-7F, 15F, 6F);
      Post3.setTextureSize(64, 64);
      Post3.mirror = true;
      setRotation(Post3, 0F, 0F, 0F);
      Post4 = new ModelRenderer(this, 0, 0);
      Post4.addBox(0F, 0F, 0F, 1, 8, 1);
      Post4.setRotationPoint(-7F, 15F, -7F);
      Post4.setTextureSize(64, 64);
      Post4.mirror = true;
      setRotation(Post4, 0F, 0F, 0F);
      Net = new ModelRenderer(this, 0, 17);
      Net.addBox(0F, 0F, 0F, 12, 8, 12);
      Net.setRotationPoint(-6F, 15F, -6F);
      Net.setTextureSize(64, 64);
      Net.mirror = true;
      setRotation(Net, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Top.render(f5);
    Bottom.render(f5);
    Post1.render(f5);
    Post2.render(f5);
    Post3.render(f5);
    Post4.render(f5);
    Net.render(f5);
  }

public void renderModel(float f5) {
    Post1.render(f5);
    Post2.render(f5);
    Post3.render(f5);
    Post4.render(f5);
    Top.render(f5);
    Bottom.render(f5);
    Net.render(f5);
}
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
