// Java generated by Techne

package com.kraz.minehr.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelOilLamp extends ModelBase
{
    //fields
    ModelRenderer Base;
    ModelRenderer Stem;
    ModelRenderer Glass;

    public ModelOilLamp()
    {
        textureWidth = 32;
        textureHeight = 32;

        Base = new ModelRenderer(this, 0, 0);
        Base.addBox(-3F, -4F, -3F, 6, 4, 6);
        Base.setRotationPoint(0F, 24F, 0F);
        Base.setTextureSize(32, 32);
        Base.mirror = true;
        setRotation(Base, 0F, 0F, 0F);
        Stem = new ModelRenderer(this, 16, 10);
        Stem.addBox(-1F, 0F, -1F, 2, 1, 2);
        Stem.setRotationPoint(0F, 19F, 0F);
        Stem.setTextureSize(32, 32);
        Stem.mirror = true;
        setRotation(Stem, 0F, 0F, 0F);
        Glass = new ModelRenderer(this, 0, 10);
        Glass.addBox(-2F, -8F, -2F, 4, 8, 4);
        Glass.setRotationPoint(0F, 19F, 0F);
        Glass.setTextureSize(32, 32);
        Glass.mirror = true;
        setRotation(Glass, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Base.render(f5);
        Stem.render(f5);
        Glass.render(f5);
    }

    public void renderModel(float f5) {
        Base.render(f5);
        Stem.render(f5);
        Glass.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
    {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}
